#!/usr/bin/zsh
cmd=$1
build_dir="./builddir"

if [ "test" = "$cmd" ]; then
    if [ $# -gt 1 ]; then
        meson test $2 -C $build_dir
    else
        meson test -C $build_dir
    fi
elif [ "config" = "$cmd" ]; then
    meson setup $build_dir --wipe -Dprefix=$(pwd)/output
elif [ "compile" = "$cmd" ]; then
    meson compile -C $build_dir
elif [ "install" = "$cmd" ]; then
    meson install -C $build_dir
elif [ "exec" = "$cmd" ]; then
    ./$build_dir/app/auto_aim
fi
