[camera]
initialization = false
capture = false

[port]
initialization = false
inspect_data = false

[detector.lightbar]
show_detail = true

[detector.armor]
show_detail = true
procedure_detail = true
