[threshold]
brightness = 20
color = 35

[light_bar]
min_area = 30.0
max_area = 5e4
min_solidity = 0.5
min_aspect_ratio = 1.5
max_aspect_ratio = 15
max_angle = 60.0

[armor]
big_armor_ratio = 3.0
small_armor_ratio = 1.6
max_angle_diff = 15
max_height_diff_ratio = 0.6
max_Y_diff_ratio = 2.0
min_X_diff_ratio = 0.5
min_aspect_ratio = 1.0
max_aspect_ratio = 4.5
min_area = 100
max_roll_angle = 60.0
max_light_bar_armor_area_ratio = 0.5 # 灯条面积最多占装甲板的比例: 50%
area_normalized_base = 1000.0
sight_offset_normalized_base = 200.0
lightbar_area_threshold = 5