[threshold]
brightness = 100
color = 120

[light_bar]
min_ratio = 0.1
max_ratio = 0.4
max_angle = 45.0

[armor]
min_light_ratio = 0.7
min_small_center_distance = 0.8
max_small_center_distance = 3.2
min_large_center_distance = 3.2
max_large_center_distance = 5.5
max_angle = 45.0

[classifier]
threshold = 0.6 # 置信度阈值. [0, 1]

[mlp]
threshold = 100
ignore_class = []
model_path = "./mlp.onnx"
labels = ["1", "2", "3", "4", "5", "outpost", "guard", "base", "negative"]

# [light_bar]
# min_area = 30.0
# max_area = 5e4

# #? CMinS = (contour 面积) 除以 (其凸包面积)
# contour_min_solidity = 0.5
# ellipse_min_aspect_ratio = 1.5
# ellipse_max_aspect_ratio = 15
# max_angle = 60.0

# [armor]
# max_angle_diff = 15
# max_height_diff_ratio = 0.6
# max_Y_diff_ratio = 2.0
# min_X_diff_ratio = 0.5
# big_armor_ratio = 2.9
# min_aspect_ratio = 1.0
# max_aspect_ratio = 4.5
# min_area = 100
# max_roll_angle = 60.0
# max_light_bar_armor_area_ratio = 0.5
# area_normalized_base = 1000.0
# sight_offset_normalized_base = 200.0
